version: '3'
services:
  selenium-chrome:
    environment:
      - DISPLAY=:0
      - HEADLESS
      - PRINT_PAGE_SOURCE_ON_FAILURE
      - RUNSLOW
    build: .
    volumes:
      - .:/code
    expose:
      - "4444"
    ports:
      - "5900"
    shm_size: 2g
