---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.8-slim
inputs:
  - name: os-automation
  - name: listen-os-cms
  - name: circleci-output
outputs:
  - name: message-output
run:
  path: bash
  args:
    - -exc
    - |
      python os-automation/.concourse/tasks/version-message/script.py | tee message-output/out.txt
